src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"uuid"}, message="There is already an account with this uuid")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $uuid;

    /**
     * @ORM\Column(type="json")
     *
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;


    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Name;

    /**
     * @ORM\OneToOne(targetEntity=UserInfo::class, cascade={"persist", "remove"}, fetch="EAGER")
     */
    private $user_info;

    /**
     * @ORM\OneToMany(targetEntity=FavoritesClusters::class, mappedBy="inspectorId")
     */
    private $clustersId;

    /**
     * @ORM\OneToMany(targetEntity=PurchasesDump::class, mappedBy="user")
     */
    private $purchasesDumps;

    /**
     * @ORM\OneToMany(targetEntity=PurchaseNote::class, mappedBy="curator")
     */
    private $purchaseNotes;

    /**
     * @ORM\OneToMany(targetEntity=ClusterAddresses::class, mappedBy="user")
     */
    private $clusterAddresses;

    /**
     * @ORM\OneToMany(targetEntity=ReadinessMapArchive::class, mappedBy="user")
     */
    private $readinessMapArchives;

    /**
     * @ORM\OneToMany(targetEntity=RepairDump::class, mappedBy="user")
     */
    private $repairDumps;

    /**
     * @ORM\ManyToMany(targetEntity=UserTags::class, mappedBy="users")
     */
    private $userTags;

    /**
     * @ORM\OneToMany(targetEntity=SheetWorkzone::class, mappedBy="user")
     */
    private $sheetWorkzones;

    /**
     * @ORM\OneToMany(targetEntity=ApiToken::class, mappedBy="user")
     */
    private $apiTokens;

    /**
     * @ORM\OneToMany(targetEntity=UsersEvents::class, mappedBy="user")
     */
    private $usersEvents;

    /**
     * @ORM\OneToMany(targetEntity=ReadinessMapCheck::class, mappedBy="user")
     */
    private $readinessMapChecks;

    /**
     * @ORM\OneToMany(targetEntity=CompitenceProfile::class, mappedBy="user")
     */
    private $compitenceProfiles;

    /**
     * @ORM\OneToOne(targetEntity=CofinancingFunds::class, mappedBy="user", cascade={"persist", "remove"})
     */
    private $cofinancingFunds;

    /**
     * @ORM\OneToMany(targetEntity=CofinancingScenario::class, mappedBy="user")
     */
    private $cofinancingScenarios;

    /**
     * @ORM\OneToMany(targetEntity=UAVsTypeEquipment::class, mappedBy="user")
     */
    private $uAVsTypeEquipment;

    /**
     * @ORM\OneToOne(targetEntity=CofinancingComment::class, mappedBy="user", cascade={"persist", "remove"})
     */
    private $cofinancingComment;

    /**
     * @ORM\OneToOne(targetEntity=UAVsCertificate::class, mappedBy="user", cascade={"persist", "remove"})
     */
    private $uAVsCertificate;

    /**
     * @ORM\OneToMany(targetEntity=ClusterContact::class, mappedBy="user")
     */
    private $clusterContacts;
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    public function setUuid(string $uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }


    function __construct()
    {
        $this->setUserInfo(new UserInfo());
        $this->clustersId = new ArrayCollection();
        $this->purchasesDumps = new ArrayCollection();
        $this->purchaseNotes = new ArrayCollection();
        $this->clusterAddresses = new ArrayCollection();
        $this->readinessMapArchives = new ArrayCollection();
        $this->repairDumps = new ArrayCollection();
        $this->userTags = new ArrayCollection();
        $this->sheetWorkzones = new ArrayCollection();
        $this->apiTokens = new ArrayCollection();
        $this->usersEvents = new ArrayCollection();
        $this->readinessMapChecks = new ArrayCollection();
        $this->compitenceProfiles = new ArrayCollection();
        $this->cofinancingScenarios = new ArrayCollection();
        $this->uAVsTypeEquipment = new ArrayCollection();
        $this->clusterContacts = new ArrayCollection();
    }


    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->uuid;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->uuid;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }



    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(?string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getUserInfo(): ?UserInfo
    {
        return $this->user_info;
    }

    public function setUserInfo(?UserInfo $user_info): self
    {
        $this->user_info = $user_info;

        return $this;
    }

    /**
     * @return Collection<int, FavoritesClusters>
     */
    public function getClustersId(): Collection
    {
        return $this->clustersId;
    }

    public function addClustersId(FavoritesClusters $clustersId): self
    {
        if (!$this->clustersId->contains($clustersId)) {
            $this->clustersId[] = $clustersId;
            $clustersId->setInspectorId($this);
        }

        return $this;
    }

    public function removeClustersId(FavoritesClusters $clustersId): self
    {
        if ($this->clustersId->removeElement($clustersId)) {
            // set the owning side to null (unless already changed)
            if ($clustersId->getInspectorId() === $this) {
                $clustersId->setInspectorId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, PurchasesDump>
     */
    public function getPurchasesDumps(): Collection
    {
        return $this->purchasesDumps;
    }

    public function addPurchasesDump(PurchasesDump $purchasesDump): self
    {
        if (!$this->purchasesDumps->contains($purchasesDump)) {
            $this->purchasesDumps[] = $purchasesDump;
            $purchasesDump->setUser($this);
        }

        return $this;
    }

    public function removePurchasesDump(PurchasesDump $purchasesDump): self
    {
        if ($this->purchasesDumps->removeElement($purchasesDump)) {
            // set the owning side to null (unless already changed)
            if ($purchasesDump->getUser() === $this) {
                $purchasesDump->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, PurchaseNote>
     */
    public function getPurchaseNotes(): Collection
    {
        return $this->purchaseNotes;
    }

    public function addPurchaseNote(PurchaseNote $purchaseNote): self
    {
        if (!$this->purchaseNotes->contains($purchaseNote)) {
            $this->purchaseNotes[] = $purchaseNote;
            $purchaseNote->setCurator($this);
        }

        return $this;
    }

    public function removePurchaseNote(PurchaseNote $purchaseNote): self
    {
        if ($this->purchaseNotes->removeElement($purchaseNote)) {
            // set the owning side to null (unless already changed)
            if ($purchaseNote->getCurator() === $this) {
                $purchaseNote->setCurator(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ClusterAddresses>
     */
    public function getClusterAddresses(): Collection
    {
        return $this->clusterAddresses;
    }

    public function addClusterAddress(ClusterAddresses $clusterAddress): self
    {
        if (!$this->clusterAddresses->contains($clusterAddress)) {
            $this->clusterAddresses[] = $clusterAddress;
            $clusterAddress->setUser($this);
        }

        return $this;
    }

    public function removeClusterAddress(ClusterAddresses $clusterAddress): self
    {
        if ($this->clusterAddresses->removeElement($clusterAddress)) {
            // set the owning side to null (unless already changed)
            if ($clusterAddress->getUser() === $this) {
                $clusterAddress->setUser(null);
            }
        }

        return $this;
    }

templates/region_readiness_map/editInfrastructureSheet.html.twig
{% extends 'default/base.html.twig' %}
{% block styles %}
 <link href="{{ asset('css/plugins/select2/select2.min.css') }}" rel="stylesheet" />
    <style>
        .select2-container {
            min-width: 100px;
            /*min-height: 500px;*/
        }

        .select2-results__option {
            padding-right: 20px;
            vertical-align: middle;
            /*min-height: 100px;*/
        }
        #make_certificate_form_UGPS {
            /*padding-right: 20px;*/
            /*vertical-align: middle;*/
            max-height: 750px;
        }
        .select2-results__option:before {
            content: "";
            display: inline-block;
            position: relative;
            height: 20px;
            width: 20px;
            border: 2px solid #e9e9e9;
            border-radius: 4px;
            background-color: #fff;
            margin-right: 20px;
            vertical-align: middle;


        }


        .select2-results__option[aria-selected=true]:before {
            content: "\f00c";
            color: #fff;
            background-color: #f77750;
            border: 0;
            display: inline-block;
            padding-left: 3px;
        }
        .select2-container--default .select2-results__option[aria-selected=true] {
            background-color: #fff;
        }
        .select2-container--default .select2-results__option--highlighted[aria-selected] {
            background-color: #eaeaeb;
            color: #272727;
        }
        .select2-container--default .select2-selection--multiple {
            margin-bottom: 10px;
        }
        .select2-container--default.select2-container--open.select2-container--below .select2-selection--multiple {
            border-radius: 4px;
        }
        .select2-container--default.select2-container--focus .select2-selection--multiple {
            border-color: #f77750;
            border-width: 2px;
        }
        .select2-container--default .select2-selection--multiple {
            border-width: 2px;
        }
        .select2-container--open .select2-dropdown--below {

            border-radius: 6px;
            box-shadow: 0 0 10px rgba(0,0,0,0.5);
            /*min-height: 500px;*/
        }


    </style>
{% endblock %}
{% block content %}
    {% import _self as formMacros %}


    <div class="row mt-3">
        <div class="col-lg-12 mb-2">
            <a href="{{ path('app_region_view_zone', {'id': zone.getId()}) }}">
                <button class="btn btn-success mb-3" type="button">
                    <i class="fa fa-arrow-left">
                        Назад
                    </i>
                </button>
            </a>
            <div class="ibox border-bottom">

                <div class="ibox-title">
                    <h5>
                        Редактирование инфраструктурного листа
                    </h5>

                </div>
                {% macro printZoneInfrastructureSheets(sheet) %}

                        {#{{ dump(sheet.vars.value) }}#}
                        <td>
                         {{ form_row(sheet.ProcurementProcedures) }}
                        </td>
                        {% if sheet.vars.value %}
                            {% set totalNumber = sheet.vars.value.totalNumber %}

                            <td>
                                {{ form_row(sheet.factNumber, {'type': 'number', 'attr': {'max':totalNumber}}) }}
                            </td>
                             <td>
                                {{ form_row(sheet.putIntoOperation, {'type': 'number', 'attr': {'max':totalNumber}}) }}
                            </td>
                        {% else %}
                             <td>
                                {{ form_row(sheet.factNumber, {'type': 'number'}) }}
                             </td>
                             <td>
                                {{ form_row(sheet.putIntoOperation, {'type': 'number'}) }}
                            </td>
                        {% endif %}

                        {% if sheet.vars.value %}
                        <td>
                         {% set funds = sheet.vars.value.funds %}
                            {% if 'В наличии' in funds %}
                                {{ form_row(sheet.deliveryDate, {'disabled' : true}) }}
                            {% else %}
                                {{ form_row(sheet.deliveryDate) }}
                            {% endif %}

                        </td>
                        {% else %}
                            <td> {{ form_row(sheet.deliveryDate) }}</td>
                        {% endif %}
                        <td>{{ form_row(sheet.OKPD2) }}</td>
                        <td>{{ form_row(sheet.KTRU) }}</td>
                         {% if sheet.vars.value %}
                            {% set showModel = sheet.vars.value.isHasModel %}
                            {% if showModel %}
                               <td>{{ form_row(sheet.model, {'disabled' : true}) }}</td>
                            {% else %}
                                <td>{{ form_row(sheet.model) }}</td>
                            {% endif %}
                        {% else %}
                            <td>{{ form_row(sheet.model) }}</td>
                        {% endif %}
                        <td>{{ form_row(sheet.countryOfOrigin) }}</td>

                        <td>
                            {{ form_row(sheet.comment) }}
                        </td>


                {% endmacro %}
                {% set thead %}
                    <tr>
                        <td class="col-md-2">Наименование</td>
                        <td class="col-md-1">Общее кол-во</td>
                        <td class="col-md-1">
                        ID закупки
                        </td>
                        <td class="col-md-1">Фактическое кол-во</td>
                        <td class="col-md-1">Введено в эксплуатацию</td>
                        <td class="col-md-1">Дата поставки (Планируемая)</td>
                        <td class="col-md-1">ОКПД2</td>
                        <td class="col-md-1">КТРУ</td>
                        <td class="col-md-1">Марка / модель</td>
                        <td class="col-md-1">Страна-производитель</td>
                        <td class="col-md-3">Комментарий</td>

                    </tr>
                {% endset %}
            <div class="ibox-content">
                {{ form_start(form) }}
                <table class="table table-bordered">

                    <thead>
                        <tr>
                            <td colspan="10">
                                <h3>Общая зона</h3>
                            </td>
                        </tr>
                        {{ thead }}
                    </thead>

                    <tbody class="sheets " id="sheets"
                           data-index="{{ form.zoneInfrastructureSheets|length > 0 ? form.zoneInfrastructureSheets|last.vars.name + 1 : 0 }}"
                           data-prototype='{{ formMacros.printZoneInfrastructureSheets(form.zoneInfrastructureSheets.vars.prototype|e) }}'
                           data-widget-tags="{{
                           '<tr></tr>'|e
                           }}"
                           data-widget-counter="{{ form.zoneInfrastructureSheets|length }}"
                    >
                        {% for sheet in form.zoneInfrastructureSheets %}
                        {% set zone_type = sheet.vars.value.zoneType %}
                            {% if zone_type == 'Общая зона' %}
                                <tr>
                                    <td>{{ sheet.vars.value.name }}</td>
                                    <td>{{ sheet.vars.value.totalNumber }}</td>
                                    {{ formMacros.printZoneInfrastructureSheets(sheet) }}
                                </tr>
                            {% endif %}

                        {% endfor %}

                    </tbody>
                </table>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <td colspan="10">
                                <h3>Рабочее место учащегося</h3>
                            </td>
                        </tr>
                        {{ thead }}
                    </thead>

                    <tbody class="sheets " id="sheets"

                    >
                        {% for sheet in form.zoneInfrastructureSheets %}
                        {% set zone_type = sheet.vars.value.zoneType %}
                            {% if zone_type == 'Рабочее место учащегося' %}
                                <tr>
                                    <td>{{ sheet.vars.value.name }}</td>
                                    <td>{{ sheet.vars.value.totalNumber }}</td>
                                    {{ formMacros.printZoneInfrastructureSheets(sheet) }}
                                </tr>
                            {% endif %}

                        {% endfor %}

                    </tbody>
                </table>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <td colspan="10">
                                <h3>Рабочее место преподавател</h3>
                            </td>
                        </tr>
                       {{ thead }}
                    </thead>

                    <tbody class="sheets " id="sheets"

                    >
                        {% for sheet in form.zoneInfrastructureSheets %}
                        {% set zone_type = sheet.vars.value.zoneType %}
                            {% if zone_type == 'Рабочее место преподавателя' %}
                                <tr>
                                    <td>{{ sheet.vars.value.name }}</td>
                                    <td>{{ sheet.vars.value.totalNumber }}</td>
                                    {{ formMacros.printZoneInfrastructureSheets(sheet) }}
                                </tr>
                            {% endif %}

                        {% endfor %}

                    </tbody>
                </table>

                    <div class="ibox-footer">
                        {{ form_row(form.submit) }}
                    </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script src="{{ asset('js/popper.min.js') }}"></script>
    <script src="{{ asset('js/inspinia.js') }}"></script>
    <script src="{{ asset('js/plugins/validate/jquery.validate.min.js') }}"></script>
    <script src="{{ asset('js/plugins/mask-plugin/jquery.mask.min.js') }}"></script>
      <script src="{{ asset('js/plugins/select2/select2.full.min.js') }}"></script>
    <script>
        $(document).ready(function(){
            $("form").validate();
            $.validator.messages.minlength = $.validator.format("Указан неполный код.");
            $.validator.addClassRules({
                okpd2 : {
                    minlength: 12
                },
                ktru : {
                    minlength: 19
                }
            });


            $('.select2').select2({
                closeOnSelect : false,
                placeholder : "...",
                allowHtml: true,
                allowClear: true
            });
        });
    </script>
{% endblock %}

templates/region_readiness_map/editRepairZone.html.twig
{% extends 'default/base.html.twig' %}

{% block content %}

    <div class="row mt-3">
        <div class="col-lg-6 offset-lg-3 договоmb-2">
            <a href="{{ path('app_region_view_zone', {'id': zone.getId()}) }}">
                <button class="btn btn-success mb-3" type="button">
                    <i class="fa fa-arrow-left">
                        Назад
                    </i>
                </button>
            </a>
            <div class="ibox border-bottom">

                    <div class="ibox-title">
                        <h5>
                            Изменение состояния ремонта. Зона - {{ zone.getName() }}
                        </h5>
                    </div>

                {{ form_start(form) }}
                <div class="ibox-content" style="display: block;">

                    <div class="form-group">
                        {{ form_widget(form.notPlanned) }}
                        <label>Ремонт не запланирован</label>
                    </div>
                    <div class="form-group">
                        {{ form_row(form.Dismantling, {'type': 'number'}) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(form.plasteringAndCommunication, {'type': 'number'}) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(form.finishing, {'type': 'number'}) }}
                    </div>
                    <div class="form-group" >
                        {{ form_row(form.branding, {'type': 'number'}) }}
                    </div>
                    <div class="form-group">
                        <label>Дата окончания</label>
                        <br>
                        {{ form_widget(form.endDate) }}

                    </div>
                    <div class="form-group">
                        <label>Фотографии</label>
                        <br>
                        {{ form_widget(form.images) }}
                        {% if error is defined %}

                        <label class="error">
                            {{ error }}
                        </label>
                        {% endif %}

                    </div>
                    <div class="form-group">
                        {{ form_row(form.comment) }}
                    </div>

                </div>
                <div class="ibox-footer ">
                    <div class="row ml-2">
                        {{ form_row(form.submit) }}
                        <a href="{{ path('app_region_view_zone', {'id': zone.getId()}) }}">
                            <button class="btn btn-outline-danger ml-3" type="button">
                                <i class="fa fa-close">
                                    Отмена
                                </i>
                            </button>
                        </a>
                    </div>

                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>



{% endblock %}

{% block scripts %}
    <script src="{{ asset('js/popper.min.js') }}"></script>
    <script src="{{ asset('js/inspinia.js') }}"></script>
    <script>
        $(document).ready(function(){
           let notPlanned = $('#edit_zone_repair_form_notPlanned');
           let dismalting = $('#edit_zone_repair_form_Dismantling');
           let plasteringAndCommunication = $('#edit_zone_repair_form_plasteringAndCommunication');
           let finishing = $('#edit_zone_repair_form_finishing');

            function setDisabled(value, ...args) {
                for (i = 0; i < args.length; i++){
                    args[i].prop('disabled',value);
                    if(value){
                        args[i].val("");
                    }
                }
            }

           function notPlannedChage() {
               if(notPlanned.is(':checked'))
               {
                   dismalting.val(100);
                   plasteringAndCommunication.val(100);
                   finishing.val(100);

                   setDisabled(true, dismalting, plasteringAndCommunication, finishing);
               }
                else{
                   setDisabled(false, dismalting, plasteringAndCommunication, finishing);
               }


           }

           notPlanned.change(notPlannedChage);

           notPlannedChage();
        });
    </script>
{% endblock %}